# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rainFall.ui'
#
# Created: Wed Jul 03 12:55:13 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(421, 473)
        self.textEdit = QtGui.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(10, 80, 401, 171))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 270, 181, 191))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 161, 165))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.comboBox_ComPort = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_ComPort.setObjectName(_fromUtf8("comboBox_ComPort"))
        self.comboBox_ComPort.addItem(_fromUtf8(""))
        self.comboBox_ComPort.addItem(_fromUtf8(""))
        self.comboBox_ComPort.addItem(_fromUtf8(""))
        self.comboBox_ComPort.addItem(_fromUtf8(""))
        self.comboBox_ComPort.addItem(_fromUtf8(""))
        self.comboBox_ComPort.addItem(_fromUtf8(""))
        self.comboBox_ComPort.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.comboBox_ComPort)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_Baudrate = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_Baudrate.setEditable(False)
        self.comboBox_Baudrate.setObjectName(_fromUtf8("comboBox_Baudrate"))
        self.comboBox_Baudrate.addItem(_fromUtf8(""))
        self.comboBox_Baudrate.addItem(_fromUtf8(""))
        self.comboBox_Baudrate.addItem(_fromUtf8(""))
        self.comboBox_Baudrate.addItem(_fromUtf8(""))
        self.comboBox_Baudrate.addItem(_fromUtf8(""))
        self.comboBox_Baudrate.addItem(_fromUtf8(""))
        self.comboBox_Baudrate.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox_Baudrate)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_2 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.comboBox_4 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.comboBox_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.comboBox_5 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBox_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.pushButton_3 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(200, 270, 211, 81))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.widget = QtGui.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(10, 20, 191, 54))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pushButton = QtGui.QPushButton(self.widget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_3.addWidget(self.pushButton)
        self.pushButton_4 = QtGui.QPushButton(self.widget)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.verticalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_2 = QtGui.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 400, 191, 61))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 401, 61))
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setPixmap(QtGui.QPixmap(_fromUtf8("logo.png")))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))

        self.retranslateUi(Dialog)
        self.comboBox_Baudrate.setCurrentIndex(1)
        self.comboBox_2.setCurrentIndex(4)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.close)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.getData)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.connectSerial)
        QtCore.QObject.connect(self.comboBox_ComPort, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), Dialog.changedSerialConfig)
        QtCore.QObject.connect(self.comboBox_2, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), Dialog.changedSerialConfig)
        QtCore.QObject.connect(self.comboBox_4, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), Dialog.changedSerialConfig)
        QtCore.QObject.connect(self.comboBox_5, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), Dialog.changedSerialConfig)
        QtCore.QObject.connect(self.comboBox_Baudrate, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), Dialog.changedSerialConfig)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.saveData)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox.setTitle(_translate("Dialog", "통신설정", None))
        self.label_3.setText(_translate("Dialog", "통신포트", None))
        self.comboBox_ComPort.setItemText(0, _translate("Dialog", "COM1", None))
        self.comboBox_ComPort.setItemText(1, _translate("Dialog", "COM2", None))
        self.comboBox_ComPort.setItemText(2, _translate("Dialog", "COM3", None))
        self.comboBox_ComPort.setItemText(3, _translate("Dialog", "COM4", None))
        self.comboBox_ComPort.setItemText(4, _translate("Dialog", "COM5", None))
        self.comboBox_ComPort.setItemText(5, _translate("Dialog", "COM6", None))
        self.comboBox_ComPort.setItemText(6, _translate("Dialog", "COM7", None))
        self.label.setText(_translate("Dialog", "통신속도", None))
        self.comboBox_Baudrate.setItemText(0, _translate("Dialog", "4800", None))
        self.comboBox_Baudrate.setItemText(1, _translate("Dialog", "9600", None))
        self.comboBox_Baudrate.setItemText(2, _translate("Dialog", "14400", None))
        self.comboBox_Baudrate.setItemText(3, _translate("Dialog", "19200", None))
        self.comboBox_Baudrate.setItemText(4, _translate("Dialog", "38400", None))
        self.comboBox_Baudrate.setItemText(5, _translate("Dialog", "57600", None))
        self.comboBox_Baudrate.setItemText(6, _translate("Dialog", "115200", None))
        self.label_2.setText(_translate("Dialog", "데이터비트", None))
        self.comboBox_2.setItemText(0, _translate("Dialog", "4", None))
        self.comboBox_2.setItemText(1, _translate("Dialog", "5", None))
        self.comboBox_2.setItemText(2, _translate("Dialog", "6", None))
        self.comboBox_2.setItemText(3, _translate("Dialog", "7", None))
        self.comboBox_2.setItemText(4, _translate("Dialog", "8", None))
        self.label_4.setText(_translate("Dialog", "패리티비트", None))
        self.comboBox_4.setItemText(0, _translate("Dialog", "없음", None))
        self.comboBox_4.setItemText(1, _translate("Dialog", "홀수", None))
        self.comboBox_4.setItemText(2, _translate("Dialog", "짝수", None))
        self.label_5.setText(_translate("Dialog", "정지비트", None))
        self.comboBox_5.setItemText(0, _translate("Dialog", "1", None))
        self.comboBox_5.setItemText(1, _translate("Dialog", "1.5", None))
        self.comboBox_5.setItemText(2, _translate("Dialog", "2", None))
        self.pushButton_3.setText(_translate("Dialog", "연결", None))
        self.groupBox_2.setTitle(_translate("Dialog", "데이터 처리", None))
        self.pushButton.setText(_translate("Dialog", "데이터 요청", None))
        self.pushButton_4.setText(_translate("Dialog", "데이터 저장", None))
        self.pushButton_2.setText(_translate("Dialog", "종료", None))

